-- ─── BESPOKE CAPITAL — DATABASE SCHEMA
create extension if not exists "uuid-ossp";
create table advisors (id uuid references auth.users(id) on delete cascade primary key,name text not null,firm text,email text not null,created_at timestamptz default now());
create table clients (id uuid default uuid_generate_v4() primary key,advisor_id uuid references advisors(id) on delete cascade not null,name text not null,dob date,gender text,age integer,start_year integer,notes text,created_at timestamptz default now(),updated_at timestamptz default now());
create table family_members (id uuid default uuid_generate_v4() primary key,client_id uuid references clients(id) on delete cascade not null,name text not null,relationship text not null,dob date,gender text,age integer,study_destination text,course_duration integer,created_at timestamptz default now());
create table planning_checklist (id uuid default uuid_generate_v4() primary key,client_id uuid references clients(id) on delete cascade not null,category text not null,status text default 'pending',completed_date date,notes text,updated_at timestamptz default now());
create table fact_finding (id uuid default uuid_generate_v4() primary key,client_id uuid references clients(id) on delete cascade not null,section text not null,data jsonb default '{}'::jsonb,updated_at timestamptz default now(),unique(client_id,section));
create table insurance_policies (id uuid default uuid_generate_v4() primary key,client_id uuid references clients(id) on delete cascade not null,person text not null,policy_no text,coverage_type text,company text,product_name text,death_benefit numeric default 0,annual_premium numeric default 0,created_at timestamptz default now());
create table protection_discovery (id uuid default uuid_generate_v4() primary key,client_id uuid references clients(id) on delete cascade not null,person text not null,updated_at timestamptz default now(),unique(client_id,person));
create table goals (id uuid default uuid_generate_v4() primary key,client_id uuid references clients(id) on delete cascade not null,type text not null,name text not null,target_amount numeric,target_age integer,ret_age integer,life_exp integer,monthly_income numeric,inflation_rate numeric default 3,rate_of_return numeric default 5,legacy_on boolean default false,legacy_amt numeric,cont_inv boolean default false,post_rate numeric default 3,ret_inc numeric,sort_order integer default 0,created_at timestamptz default now());
create table investments (id uuid default uuid_generate_v4() primary key,client_id uuid references clients(id) on delete cascade not null,name text not null,product_type text,mode text default 'Regular',start_date text,end_date text,monthly_contribution numeric default 0,lump_sum numeric default 0,current_value numeric default 0,irr numeric,created_at timestamptz default now());
create table recommendations (id uuid default uuid_generate_v4() primary key,client_id uuid references clients(id) on delete cascade not null,shortfall_type text,product_name text,coverage_amount numeric,premium_monthly numeric,notes text,sort_order integer default 0,created_at timestamptz default now());
create table plan_settings (id uuid default uuid_generate_v4() primary key,client_id uuid references clients(id) on delete cascade not null,global_return numeric default 5,global_inflation numeric default 3,updated_at timestamptz default now(),unique(client_id));
alter table advisors enable row level security;
alter table clients enable row level security;
alter table family_members enable row level security;
alter table planning_checklist enable row level security;
alter table fact_finding enable row level security;
alter table insurance_policies enable row level security;
alter table protection_discovery enable row level security;
alter table goals enable row level security;
alter table investments enable row level security;
alter table recommendations enable row level security;
alter table plan_settings enable row level security;
create policy "advisors_own" on advisors for all using (auth.uid() = id);
create policy "clients_own" on clients for all using (advisor_id = auth.uid());
create policy "family_own" on family_members for all using (client_id in (select id from clients where advisor_id = auth.uid()));
create policy "checklist_own" on planning_checklist for all using (client_id in (select id from clients where advisor_id = auth.uid()));
create policy "ff_own" on fact_finding for all using (client_id in (select id from clients where advisor_id = auth.uid()));
create policy "policies_own" on insurance_policies for all using (client_id in (select id from clients where advisor_id = auth.uid()));
create policy "protection_own" on protection_discovery for all using (client_id in (select id from clients where advisor_id = auth.uid()));
create policy "goals_own" on goals for all using (client_id in (select id from clients where advisor_id = auth.uid()));
create policy "investments_own" on investments for all using (client_id in (select id from clients where advisor_id = auth.uid()));
create policy "recs_own" on recommendations for all using (client_id in (select id from clients where advisor_id = auth.uid()));
create policy "settings_own" on plan_settings for all using (client_id in (select id from clients where advisor_id = auth.uid()));
create or replace function public.handle_new_user() returns trigger as $$ begin insert into public.advisors (id,name,email) values (new.id,coalesce(new.raw_user_meta_data->>'name',split_part(new.email,'@',1)),new.email); return new; end; $$ language plpgsql security definer;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
